config/routes.rb
Betastore::Application.routes.draw do

  root :to => 'products#index'
  resources :subscriptions

  get '/products' => 'products#index', as: 'products'
  get '/products/:id' => 'products#show', as: 'product'

  post '/products/:product_id/add_to_cart' => 'carts#update', as: 'add_to_cart'
  get '/cart' => 'carts#show', as: 'cart'

  get  '/checkout' => 'orders#new', as: 'checkout'
  post '/checkout' => 'orders#create'

  put '/order' => 'orders#update', as: 'order'

  namespace :admin do
    resources :products
  end

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  has_many :line_items, :through => :orders
  has_many :products, :through => :line_items

  before_validation :downcase_email
  before_validation :upcase_state

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /@/, allow_blank: true }
  validates :state, inclusion: %w(AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY)
  validates :zip_code, format: { with: /\d{5,}/, allow_blank: true }

  private
  def downcase_email
    self.email = email.to_s.downcase
  end

  def upcase_state
    self.state = state.to_s.upcase
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  belongs_to :credit_card
  belongs_to :shipping_address
  has_many :line_items
  has_many :products, :through => :line_items

  accepts_nested_attributes_for :line_items,
    :credit_card,
    :shipping_address

  def self.from_cart(cart)
    order = new
    cart.each do |product_id, quantity|
      order.line_items.build(
        product: Product.find(product_id),
        quantity: quantity
      )
    end
    order
  end

  def total_price
    line_items.to_a.sum(&:total_price)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, :through => :line_items

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def self.incredible
    where("name like 'Incredible%'")
  end

  def self.cheap
    where("price < 50")
  end
end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @products = Product.order('name').all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: "Product #{@product.id} was created"
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: "Product #{@product.id} was updated"
    else
      render 'edit'
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to admin_products_path, notice: "Product #{product.id} was deleted"
  end

  private
  def product_params
    params.require(:product).permit!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def update
    session[:cart] ||= {}
    cart = session[:cart]
    product_id = params[:product_id]

    if product_id.present?
      cart[product_id] ||= 0
      cart[product_id] += 1
    end
    redirect_to cart_path, alert: 'Item was added to cart'
  end

  def show
    @order = Order.from_cart(session[:cart])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.from_cart(session[:cart])
    @order.build_credit_card
    @order.build_shipping_address
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    cart_params = params[:order][:line_items_attributes]
    logger.debug "cart_params: #{cart_params.values.inspect}"
    logger.debug "cart: #{session[:cart].inspect}"

    new_cart = {}

    for item in cart_params.values
      new_cart[item["product_id"]] = item["quantity"].to_i
    end

    logger.debug "new_cart: #{new_cart.inspect}"
    session[:cart] = new_cart

    redirect_to cart_path, notice: 'Your cart was updated'
  end

private
  def order_params
    params.permit(
      :line_items_attributes =>
        [:product_id, :quantity],
      :credit_card_attributes =>
        [:card_number],
      :shipping_address_attributes =>
        [:street, :city, :state, :zip])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order('name')
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/admin/products/_form.html.erb
<% if @product.errors.present? %>
  <p>
    <h2>There was an error</h2>
    <% for error in @product.errors.full_messages %>
      <%= error %>
    <% end %>
  </p>
<% end %>

<%= form_for [:admin, @product], html: { class: "form-horizontal", role: "form" } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image_url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.url_field :image_url, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li><%= link_to @product.name, admin_product_path(@product) %></li>
  <li class="active">Edit Product</li>
</ol>

<%= render 'form' %>

app/views/admin/products/index.html.erb
<h1>Products</h1>

<!-- I'm a comment -->

<%# I'm a Ruby comment %>

<p><%= link_to "Add New Product", new_admin_product_path, class: 'btn btn-primary' %></p>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Created At</th>
  </tr>
  <% for product in @products %>
    <tr>
      <td><%= link_to product.id, admin_product_path(product) %></td>
      <td><%= link_to product.name, admin_product_path(product) %></td>
      <td><%= number_to_currency product.price %></td>
      <td>
        <%= time_ago_in_words product.created_at %> ago
        <%= product.created_at.strftime('%a, %b %e %Y') %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/products/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li class="active">New Product</li>
</ol>

<%= render 'form' %>

app/views/admin/products/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Products", admin_products_path %></li>
  <li class="active"><%= @product.name %></li>
</ol>

<p>
  <%= image_tag @product.image_url, alt: @product.name, style: 'max-width: 600px' %>
</p>

<p>
  Price: <%= @product.price %>
</p>

<p>
  <%= link_to "Edit product", edit_admin_product_path(@product), class: 'btn btn-primary' %>
  <%= link_to "Delete product",
        admin_product_path(@product),
        method: 'delete',
        data: { confirm: 'Are you sure you want to delete this product?' },
        class: 'btn btn-danger' %>
</p>

app/views/carts/show.html.erb
<h1>Shopping Cart</h1>

<table class="table">
  <tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Base Price</th>
    <th>Total Price</th>
  </tr>
  <%= form_for @order, url: order_path, html: { method: 'put' } do |f| %>
    <%= f.fields_for :line_items do |li| %>
      <% line_item = li.object %>
      <%= li.hidden_field :product_id %>
      <tr>
        <td><%= line_item.product.name %></td>
        <td><%= li.number_field :quantity %></td>
        <td><%= number_to_currency line_item.product.price %></td>
        <td><%= number_to_currency line_item.total_price %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3">
        <%= f.submit "Update Cart", class: 'btn btn-success' %>
        <%= link_to "Checkout", checkout_path, class: 'btn btn-primary' %>
      </td>
      <td><%= number_to_currency @order.total_price %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Betastore</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Betastore Admin</a>
          </div>
        </div>
      </nav>

      <% if flash[:notice].present? %>
        <div class="notice"><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Checkout</h1>

<%= form_for @order, url: checkout_path do |f| %>
  <table class="table">
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Base Price</th>
      <th>Total Price</th>
    </tr>
    <%= f.fields_for :line_items do |li| %>
      <% line_item = li.object %>
      <%= li.hidden_field :product_id %>
      <%= li.hidden_field :quantity %>
      <tr>
        <td><%= line_item.product.name %></td>
        <td><%= line_item.quantity %></td>
        <td><%= number_to_currency line_item.product.price %></td>
        <td><%= number_to_currency line_item.total_price %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3">
      </td>
      <td><%= number_to_currency @order.total_price %></td>
    </tr>
  </table>

  <%= link_to "Edit Order", cart_path, class: 'btn btn-primary' %>

  <div class="row">
    <%= f.fields_for :credit_card do |cc| %>
      <div class="col-md-6">
        <h2>Credit Card Information</h2>

        <div class="form-group">
          <%= cc.label :number, class: "col-sm-2 control-label "%>
          <div class="col-sm-10">
            <%= cc.text_field :number, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= cc.label :expiration_date, class: "col-sm-2 control-label "%>
          <div class="col-sm-10">
            <%= cc.text_field :expiration_date, class: 'form-control' %>
          </div>
        </div>

      </div>
    <% end %>

    <%= f.fields_for :shipping_address do |sa| %>
      <div class="col-md-6">
        <h2>Shipping Information</h2>


      </div>
    <% end %>
  </div>

<% end %>

app/views/products/index.html.erb
<h1>Products!</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <%= image_tag product.image_url, class: 'img-responsive' %>
      <%= link_to product.name, product_path(product) %>
      <%= number_to_currency product.price %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p><%= @product.description %></p>

<%= link_to "Add to cart", add_to_cart_path(@product.id), class: 'btn btn-success', method: 'post' %>

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %>
        prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email, "Find out when we go live:" %>
    <%= f.text_field :email %>
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<h1>Listing subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.email %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<%= render 'form' %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>